app:
  security:
    jwt:
      keystore-location: keys/proc.jks
      keystore-password: proc123
      key-alias: proc
      private-key-passphrase: proc123

spring:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:file:./test_db;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
  redis:
    host: localhost
    port: 6379

  security:
    oauth2:
      client:
        registration:
          google:
            clientId:
            clientSecret: 
#            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile

logging:
  level:
    root: debug